<?php
use Magento\Framework\App\Action\Action;
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
//get product label helper
$productLabelHelper = $this->helper('Etatvasoft\ProductLabel\Helper\ProductLabelHelper');
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else : ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div 
                data-pr-sku='<?= $block->escapeHtml($_product->getSku())?>'
                data-pr-name='<?= $block->escapeHtml($_product->getName()) ?>'
                class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    //if there is product label found then display label
                    $productLabelType = $productLabelHelper->getProductLabelType($_product);
                    if (!empty($productLabelType)) {
                        if ($productLabelType == 'text') {
                            $productLabel = $productLabelHelper->getProductLabel($_product);
                            $productLabelColor = $productLabelHelper->getProductLabelColor($_product);
                            $productLabelBackgroundColor = $productLabelHelper->getProductLabelBackgroundColor($_product);
                            $productLabelShape = $productLabelHelper->getProductLabelShape($_product);
                            if ($productLabel && $productLabelShape) { ?>
                                <span class="product-label"
                                    <?php echo !empty($productLabelColor) ? 'data-color=' . $productLabelColor : ''; ?> <?php echo !empty($productLabelBackgroundColor) ? 'data-background-color=' . $productLabelBackgroundColor : ''; ?> <?php echo !empty($productLabelShape) ? 'data-shape=' . $productLabelShape : '' ?>>
                                    <?php echo $block->escapeHtml($productLabel); ?>
                                </span>
                            <?php }
                        } elseif ($productLabelType == 'image') {
                            $productLabelImage = $productLabelHelper->getProductLabelImage($_product);
                            if ($productLabelImage) { ?>
                                <div class="product-label-image">
                                    <img src="<?php echo $productLabelHelper->getProductMediaUrl() . $productLabelImage; ?>">
                                </div>
                            <?php }
                        }
                    }
                    ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    data-pr-sku='<?= $block->escapeHtml($_product->getSku())?>'
                                                    data-pr-name='<?= $block->escapeHtml($_product->getName()) ?>'
                                                    data-pr-price='<?= $block->escapeHtml($_product->getPrice()) ?>'
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="newAddToCart action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else : ?>
                                        <?php if ($_product->isAvailable()) : ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if (!empty($productLabelHelper->getProductLabelType($_product))) {
                        if ($productLabelHelper->getProductLabelType($_product) == 'image' && $productLabelHelper->getProductLabelImage($_product)) { ?>
                            <div class="product-label-image">
                                <img src="<?php echo $productLabelHelper->getProductMediaUrl().$productLabelHelper->getProductLabelImage($_product); ?>">
                            </div>
                        <?php }
                    }
                    ?>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
        }
    }
}
</script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'],function($) {
        $(document).ready(function() {
            //loop through all the labels found
            $('.product-label').each(function(index) {
                //set default background color & font color
                if($(this).attr('data-background-color')){
                    $(this).css("background-color", $(this).attr('data-background-color'));
                }else{
                    $(this).css("background-color", '#ff0000');
                }
                if($(this).attr('data-color')){
                    $(this).css("color", $(this).attr('data-color'));
                }else{
                    $(this).css("color", '#ffffff');
                }

                //assign css according to shapes found
                if($(this).attr('data-shape')){
                    $(this).addClass($(this).attr('data-shape'));
                }
            });
        });

        /**
         * Google Analytics Add to Cart Event for category Pages
         *  Author: Ankush
         */
        $('.newAddToCart').each(function(index) {
        
        $(this).on("click", function() {
            gtag("event", "add_to_cart", {
                'currency':"GBP",
                'value': parseFloat($(this).attr('data-pr-price')) ,
                items: [{
                    'item_name': ''+ $(this).attr('data-pr-name') + '',
                    'value': parseFloat($(this).attr('data-pr-price')) ,
                    'item_id': ''+ $(this).attr('data-pr-sku') +'',
                    'quantity': 1,

                }]
            });
        });
    })

    /**
     *  View_Item_List Google Analytics 4 event for category pages.
     *  Author: Ankush Kumar
     */

     var catgryItems = $('.item.product.product-item');
    var urlCat = window.location.pathname.toString().split("/").splice(1, 10);
    var items = [];
    var categories = {}
    if(urlCat.length > 1){
        var indx = 1
        $(urlCat).each(function(i, val) {
            categories[i == 0 ? 'item_category' : 'item_category'+ indx ] = val;
            indx += 1;

        });
    }else{
        categories = { 'item_category' : urlCat[0] }
    }

     /**
     *  Getting Product details 
     *  Author: Ankush Kumar
     */
    catgryItems.each(function(i, val) {
        var dat = {
            item_id: ""+ "" + catgryItems[i].getElementsByClassName("product-item-info")[0].getAttribute('data-pr-sku') + "",
            item_name: "" + catgryItems[i].getElementsByClassName("product-item-info")[0].getAttribute('data-pr-name') + "",
            index: i,
        }
        items.push({...categories, ...dat});  

    });


    /**
     *  Trigger event when customer lands first time on page 
     *  Author: Ankush Kumar
     */
    var hasVisited = sessionStorage.getItem('visited');
    if (hasVisited != window.location.href) {
        sessionStorage.setItem('visited', window.location.href);
        gtag("event", "view_item_list", {
            item_list_id: "" + "" + location.pathname+location.search.substr(1) + "",
            item_list_name: "" + $('#page-title-heading span[data-ui-id="page-title-wrapper"]').text() + "",
            items: items
        });

        
    }

    });
</script>

