<?php
/**
 *
 * Maghos_Gdpr Magento 2 extension
 *
 * NOTICE OF LICENSE
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * @category Maghos
 * @package Maghos_Gdpr
 * @copyright Copyright (c) 2018 Maghos s.r.o.
 * @license http://www.maghos.com/business-license
 * @author Magento dev team <support@maghos.com>
 */
/** @var $block \Maghos\Gdpr\Block\Confirm */
?>
<p><?= __('You are about to delete all personal information associated with email %1.', $block->getParam('email'))
    ?></p>
<p><?= __('This action is final and cannot be undone.') ?></p>
<p><?= __('You will still be able to make an RMA claim using an invoice.') ?></p>

<form id="confirmation-form" class="form" method="POST" action="<?= /* @noEscape */
    $block->getUrl('gdpr/delete/delete') ?>">
    <input type="hidden" name="email" value="<?= $block->escapeHtml($block->getParam('email')) ?>"/>
    <input type="hidden" name="hash" value="<?= $block->escapeHtml($block->getParam('hash')) ?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <button class="action submit primary" id="submit-form" type="button"
                    title="<?= __('Delete Personal Information') ?>">
                <span><?= __('Delete Personal Information') ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/prompt'
    ], function ($, confirmation) {
        $('#submit-form').on('click', function () {
            confirmation({
                title: '<?= __('Are you sure?') ?>',
                content: '<?= __('All Your personal information will be deleted and we wont be able to recover it anymore.') ?>',
                actions: {
                    confirm: function () {
                        $('#confirmation-form').submit();
                    }
                }
            });
        });
    });
</script>