<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**@var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
?>
<div class="messages">
    <div class="message message-notice">
        <?php echo __('Choose products the tab will be displayed for. Conditions and condition combinations allow you to narrow selection down to a specific range of products'); ?>
    </div>
</div>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>
<div class="rule-tree">
    <fieldset id="<?php /* @escapeNotVerified */ echo $_jsObjectName ?>" <?php /* @escapeNotVerified */ echo $_element->serialize(['class']) ?> class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo $_element->getLegend() ?></span></legend>
        <br>
    <?php if ($_element->getComment()): ?>
        <div class="messages">
            <div class="message message-notice"><?php echo $block->escapeHtml($_element->getComment()) ?></div>
        </div>
    <?php endif; ?>
    <div class="rule-tree-wrapper">
        <?php echo $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "jquery",
    "prototype"
], function(VarienRulesForm, $){

window.<?php /* @escapeNotVerified */ echo $_jsObjectName ?> = new VarienRulesForm('<?php /* @escapeNotVerified */ echo $_jsObjectName ?>', '<?php /* @escapeNotVerified */ echo $block->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()): ?>
    <?php echo $_element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>

$('#<?php /* @escapeNotVerified */ echo $_jsObjectName ?>').find('.rule-chooser').each(function(index, el) {
    var ruleChooserUrl = jQuery(this).attr('url');
    ruleChooserUrl += 'form/<?php /* @escapeNotVerified */ echo $_jsObjectName ?>';
    jQuery(this).attr('url', ruleChooserUrl);
});

});
</script>
