<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<style amp-custom>
.basket__count-wrp {
	background-color: #006fc4;
}   
   
/*show more - less On containter in Categories page*/
	
.showmoretext {
    height: 80px;
    overflow: hidden;
}
.showmorecontainer {
    position: relative;
}
.showmorecontainer label{
    position: absolute;
    top: 100%;
}
.showmorecontainer input {
    display: none;
}
.showmorecontainer label:after {
    content: "--Show More--";
	color:blue;
    
	
}
.showmorecontainer input:checked + label:after {
    content: "--Show Less--";
	color:blue;
	
}
.showmorecontainer input:checked ~ div {
    height: 100%;
}
 .showmorecontainer a:link {
  color: blue;
  text-decoration: underline;
}
.showmorecontainer a:hover {
  color: red;
  background-color: transparent;
  text-decoration: underline;
}
.showmorecontainer  h1 {
  font: 500 20px/1.35 PT Sans, Helvetica Neue, Verdana, Arial, sans-serif;
  margin: 0 0 20px;
}

/*ENd*/	
	
/*Carousel image in product detail page*/		

.desc .carousel {
    flex-direction: column;
	}
	
.desc .carousel-container, .desc .carousel-text {
    width: 100%;
}

.desc .carousel-container {
    position: relative;
    width: 55%;
    overflow: hidden;
}
	
.desc .carousel-content {
    position: relative;
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    width: 500%;
}
	
.desc .carousel-slide {
    position: relative;
    width: 20%;
}

.desc .carousel-slide img {
    display: block;
    width: 100%;
}

.desc .carousel-text {
    padding: 20px 0;
}

	
.desc .carousel-container, .desc .carousel-text {
    width: 100%;
}
.desc .carousel-text {
    display: flex;
    flex-direction: column; 
    background-color: #f4f5f6;
    color: #333;
    overflow: hidden;
}	
	
.desc .carousel-text_selling-point {
    width: 80%;
    margin: auto;
}
	
.desc .carousel-sp_title {
    margin: 0 0 20px;
    line-height: 28px;
    font-size: 28px;
    font-weight: 400;
}
	
.desc .carousel-sp_list {
    margin: 0;
    padding-left: 0;
}
	
.desc .carousel-sp_list-item {
    list-style-type: disc;
    margin-top: 10px;
    line-height: 24px;
    font-size: 16px;
}

.desc .thumbnail {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
}

.desc .mt-10 {
    margin-top: 10px;
}
	
.desc .thumbnail-item {
    position: relative;
    display: inline-block;
    width: calc(100%/4 - 10px);
}
	
.desc .thumbnail-item:hover:after {
    background: rgba(0,0,0,0);
}
.desc .thumbnail-item:after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,.6);
    pointer-events: none;
    transition: background .2s ease;
}	
	
.product.data.items>.item.content:before, .product.data.items>.item.content:after {
    content: '';
    display: table;
}

*:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

#product-options-wrapper .product-options .textual{
   max-width: 100%;
}
	
/*End*/	
	
	
	
</style>