<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()):
    $type = 'related';
    $class = $type;
    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;
    $showWishlist = $block->displayWishList();
    $showCompare = $block->displayCompare();
    $showCart = $block->displayCart();
    $templateType = null;
    $description = false;
endif; ?>
<?php if ($exist): ?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block news-products <?php echo $class; ?>"
            data-mage-init='{
            "relatedProducts":{"relatedCheckbox":".related.checkbox"}
            }'
            data-limit="<?php echo $limit; ?>"
            data-shuffle="<?php echo $shuffle; ?>">
        <?php else: ?>
            <div class="block news-products <?php echo $class; ?>"
            data-mage-init='{"upsellProducts":{}}'
            data-limit="<?php echo $limit; ?>"
            data-shuffle="<?php echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block news-products <?php echo $class; ?>">
    <?php endif; ?>

    <div class="box-title-area">
        <h4 class="title"><?php echo $title; ?> </h4>
    </div>

    <div class="block-content content"
         aria-labelledby="block-<?php echo $class ?>-heading">
        <div class="products wrapper grid products-grid products-<?php echo $type; ?>">
            <ol class="products list items product-items related-products-carousel">
                <?php $iterator = 1; ?>
                <?php $i = 0; ?>
                <?php foreach ($items as $item): ?>
                    <?php $available = ''; ?>
                    <?php if ($i > 9):
                        break;
                    endif; ?>
                    <?php if (
                        !$item->isComposite() &&
                        $item->isSaleable()
                        && $type == 'related'
                    ): ?>
                        <?php if (!$item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?php echo ($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                    <?php else: ?>
                        <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <?php endif; ?>
                    <div class="product-item-info <?php echo $available; ?>">
                        <?php echo '<!-- ' . $image . '-->' ?>
                        <a href="<?php echo $block->getProductUrl(
                            $item
                        ) ?>"
                           class="product photo product-item-photo">
                            <?php echo $block->getImage(
                                $item,
                                $image
                        )->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   title="<?php echo $block->escapeHtml(
                                       $item->getName()
                                   ) ?>"
                                   href="<?php echo $block->getProductUrl(
                                       $item
                                   ) ?>">
                                    <?php echo $block->escapeHtml(
                                        $item->getName()
                                    ) ?>
                                </a>
                            </strong>

                            <?php echo $block->getProductPrice($item); ?>

                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml(
                                    $item,
                                    $templateType
                                ) ?>
                            <?php endif; ?>

                            <?php if (
                                $showWishlist ||
                                $showCompare ||
                                $showCart
                            ): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($item->isSaleable()): ?>
                                                <?php if ($item->getTypeInstance()
                                                    ->hasRequiredOptions($item)
                                                ): ?>
                                                    <button class="action tocart primary"
                                                            data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($item) ?>"}}'
                                                            type="button"
                                                            title="<?php echo __(
                                                                'Add to Cart'
                                                            ) ?>">
                                                        <span>
                                                            <?php echo __(
                                                                'Add to Cart'
                                                            ) ?>
                                                        </span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper(
                                                        'Magento\Framework\Data\Helper\PostHelper'
                                                    );
                                                    $postData = $postDataHelper
                                                        ->getPostData(
                                                            $block->getAddToCartUrl(
                                                                $item
                                                            ),
                                                            ['product' => $item->getEntityId()]
                                                        )
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php echo $postData; ?>'
                                                            type="button"
                                                            title="<?php echo __(
                                                                'Add to Cart'
                                                            ) ?>">
                                                        <span>
                                                            <?php echo __(
                                                                'Add to Cart'
                                                            ) ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($item->getIsSalable()): ?>
                                                    <div class="stock available">
                                                        <span>
                                                            <?php echo __(
                                                                'In stock'
                                                            ) ?>
                                                        </span>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span>
                                                            <?php echo __(
                                                                'Out of stock'
                                                            ) ?>
                                                        </span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary"
                                             data-role="add-to-links">
                                            <?php if (
                                                $this->helper(
                                                    'Magento\Wishlist\Helper\Data'
                                                )->isAllow() && $showWishlist
                                            ): ?>
                                                <a href="#"
                                                   data-post='<?php echo $block->getAddToWishlistParams(
                                                       $item
                                                   ); ?>'
                                                   class="action towishlist"
                                                   data-action="add-to-wishlist"
                                                   title="<?php echo __(
                                                       'Add to Wish List'
                                                   ) ?>">
                                                    <span>
                                                        <?php echo __(
                                                            'Add to Wish List'
                                                   )
                                                        ?>
                                                    </span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if (
                                                $block->getAddToCompareUrl() &&
                                                $showCompare
                                            ): ?>
                                                <?php
                                                $compareHelper = $this->helper(
                                                    'Magento\Catalog\Helper\Product\Compare'
                                                ); ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php echo $compareHelper->getPostDataParams(
                                                       $item
                                                   ); ?>'
                                                   data-role="add-to-links"
                                                   title="<?php echo __(
                                                       'Add to Compare'
                                                   ); ?>">
                                                    <span>
                                                        <?php echo __(
                                                            'Add to Compare'
                                                        ) ?>
                                                    </span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo (
                        $iterator == count($items) + 1
                    ) ? '</li>' : '' ?>
                    <?php $i++; ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
    </div>
    <script>
        require(['jquery', 'carouseljs'], function ($) {
            $('.related-products-carousel').owlCarousel({
                loop: true,
                margin: 10,
                responsiveClass: true,
                nav: false,
                dots: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 4
                    }
                }
            })
        });
    </script>
<?php endif;
