<?php $post = $block->getPost(); ?>
<div class="news-post-share-buttons">
    <a href="http://twitter.com/share?url=<?php echo $post->getPostUrl(); ?>&text=<?php echo $post->getTitle(); ?>"
       target="_blank" class="share-btn twitter">
        <i class="fa fa-twitter"></i>
    </a>
    <a href="https://plus.google.com/share?url=<?php echo $post->getPostUrl(); ?>"
       target="_blank"
       class="share-btn google-plus">
        <i class="fa fa-google-plus"></i>
    </a>
    <a href="http://www.facebook.com/sharer/sharer.php?u=<?php echo $post->getPostUrl(); ?>"
       target="_blank"
       class="share-btn facebook">
        <i class="fa fa-facebook"></i>
    </a>
    <a href="http://www.stumbleupon.com/submit?url=<?php echo $post->getPostUrl(); ?>&title=<?php echo $post->getTitle(); ?>"
       target="_blank" class="share-btn stumbleupon">
        <i class="fa fa-stumbleupon"></i>
    </a>
    <a href="http://reddit.com/submit?url=<?php echo $post->getPostUrl(); ?>&title=<?php echo $post->getTitle(); ?>"
       target="_blank" class="share-btn reddit">
        <i class="fa fa-reddit"></i>
    </a>
    <a href="http://www.linkedin.com/shareArticle?url=<?php echo $post->getPostUrl(); ?>&title=<?php echo $post->getTitle(); ?>"
       target="_blank" class="share-btn linkedin">
        <i class="fa fa-linkedin"></i>
    </a>
    <a href="mailto:?subject=<?php echo $post->getTitle(); ?>&body=<?php echo $post->getPostUrl(); ?>"
       target="_blank"
       class="share-btn email">
        <i class="fa fa-envelope"></i>
    </a>
</div>