<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="tabspro-swatch" data-id="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId(); ?>"></div>
<script>
    window['swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId(); ?>'] = {
        selectorProduct: '.product-item-details',
        onlySwatches: true,
        enableControlLabel: false,
        numberToShow: <?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>,
        jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
        jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
        mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>'
    }
</script>
